image: ubuntu:22.04

build:
  script:
     - apt-get update
     - apt-get install -y git curl build-essential cmake m4 libgmp-dev python3 pip openjdk-8-jdk
     - python3 -m pip install toml
     - ./contrib/setup-bison.sh
     - ./contrib/setup-flex.sh
     - ./contrib/setup-smt-switch.sh
     - ./contrib/setup-btor2tools.sh
     - ./contrib/setup-mustool.sh
     - ./configure.sh
     - cd build
     - make -j${nproc}
